apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "{{ .Values.serviceName }}"
    spec:
      containers:
      - name: "{{ .Values.serviceName }}"
        image: "qmipfu.azurecr.io/{{ .Values.dockerRepositoryName }}:{{ .Values.dockerTag }}"
        env:
            - name: ENV_PROFILE
              value: "{{ .Values.EnvProfile }}"
        ports:
        - containerPort: {{ .Values.dockerPort }}
        resources:
          limits:
            memory: "512Mi"
      imagePullSecrets:
      - name: pfu-docker-registry-secret
