apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.serviceName }}"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: {{ .Values.dockerPort }}
  selector:
    app: "{{ .Values.serviceName }}"
